version: "3.9"

services:

  clickhouse:
    image: "yandex/clickhouse-server:21.12"
    environment:
      - CLICKHOUSE_DB=uptrace
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'localhost:8123/ping' ]
      interval: 1s
      timeout: 1s
      retries: 30

  uptrace:
    build:
      context: deploys/uptrace
    ports:
      - "14317:14317/tcp" # OTLP
      - "14318:14318/tcp" # UI and HTTP API
    environment:
      - DEBUG=1
    depends_on:
      clickhouse:
        condition: service_healthy
        
  collector:
    build:
      context: deploys/collector
    ports:
      - "4317:4317/tcp"
      - "4318:4318/tcp"
    restart: on-failure
    depends_on:
      - uptrace
        
  digit:
    build:
      context: .
      dockerfile: deploys/upper/dockerfile
    restart: on-failure
    depends_on:
      - collector
    ports:
      - "5051:5000/tcp"
    environment:
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317

  lower:
    build:
      context: .
      dockerfile: deploys/lower/dockerfile
    restart: on-failure
    depends_on:
      - collector
      - digit
    ports:
      - "5052:5000/tcp"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317

  upper:
    build:
      context: .
      dockerfile: deploys/upper/dockerfile
    restart: on-failure
    depends_on:
      - collector
    ports:
      - "5053:5000/tcp"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317

  special:
    build:
      context: .
      dockerfile: deploys/upper/dockerfile
    restart: on-failure
    depends_on:
      - collector
    ports:
      - "5054:5000/tcp"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317

  generator:
    build:
      context: .
      dockerfile: deploys/generator/dockerfile
    restart: on-failure
    depends_on:
      - digit
      - lower
      - upper
      - special
    ports:
      - "5055:5000/tcp"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317

  load:
    build:
      context: .
      dockerfile: deploys/load/dockerfile
    restart: on-failure
    depends_on:
      - generator
    deploy:
      mode: replicated
      replicas: 1