FROM golang:1.18 as builder

WORKDIR /app
COPY . /app
RUN CGO_ENABLED=0 GOOS=linux GOPROXY=https://proxy.golang.org go build -o app cmd/digit/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates && addgroup -S app && adduser -S app -G app
#USER app
WORKDIR /app
EXPOSE 5000
COPY --from=builder /app/app .
ENTRYPOINT [ "./app" ]