receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  otlp:
    endpoint: uptrace:14317
    headers:
      uptrace-dsn: 'http://secret2@uptrace:14317/2'
    tls:
      insecure: true


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
